apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location /app1 {
            proxy_pass http://app1-service;
        }

        location /app2 {
            proxy_pass http://app2-service;
        }
    }
