pipeline {
    agent {
        label 'Node_Name'  // set label of Jenkins Node
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('DOCKERHUB_CREDENTIALS')
        DOCKERHUB_USERNAME = 'your_dockerhub_username' // Replace with your DockerHub username
    }
    stages {
        stage('Clone Source Code') {
            steps {
                git branch: 'main', url: 'https://github.com/crystalbd/bs23.git'
                // git branch: 'main', url: 'https://github.com/yourusername/src.git'
            }
        }       
        stage('Build') {
            steps {
                dir('app2/build') {
                    sh 'docker build -t <DOCKERHUB_USERNAME>/app1:latest .'
                }
            }
        }
        stage('Push to DockerHub') {
            steps {
                withCredentials([string(credentialsId: 'DOCKERHUB_CREDENTIALS', variable: 'DOCKERHUB')]) {
                    sh "echo $DOCKERHUB | docker login -u <DOCKERHUB_USERNAME> --password-stdin"
                    sh 'docker push <DOCKERHUB_USERNAME>/app1:latest'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'kubectl apply -f app2/deploy/app2-deployment.yaml'
                sh 'kubectl apply -f app2/deploy/app2-service.yaml'
            }
        }
    }
}
